spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Use H2 for tests
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Tenant DataSources (H2 for tests)
finny.tenant.datasource.driver-class-name=org.h2.Driver
finny.tenant.datasource.url-prefix=jdbc:h2:mem:
finny.tenant.datasource.url-suffix=;DB_CLOSE_DELAY=-1
finny.tenant.datasource.username=sa
finny.tenant.datasource.password=
