spring.application.name=finny
spring.jpa.open-in-view=false
spring.main.allow-bean-definition-overriding=true

# Master Database Auto-Config
spring.datasource.url=jdbc:mysql://localhost:3306/finny_master?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/finny_master?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tenant DataSources (Defaults to MySQL)
finny.tenant.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
finny.tenant.datasource.url-prefix=jdbc:mysql://localhost:3306/
finny.tenant.datasource.url-suffix=?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
finny.tenant.datasource.username=root
finny.tenant.datasource.password=root